[package]
name = "excel-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ratatui = "0.28.1"
strum = "0.26.3"
strum_macros = "0.26.4"
tui-input = "0.11.0"
